color0 #594141
color1 #ffb4ab
color2 #ffb3b6
color3 #ffb3b6
color4 #ffb688
color5 #ffb3b6
color6 #ffb3b6
color7 #f6dddd
color8 #a8898a
color9 #ffb4ab
color10 #ffb3b6
color11 #ffb3b6
color12 #ffb688
color13 #ffb3b6
color14 #ffb3b6
color15 #f6dddd

cursor                #f6dddd
cursor_text_color     #1d1011
background            #1d1011
foreground            #f6dddd
selection_foreground  #e0bebf
selection_background  #594141
active_border_color   #ffb3b6
inactive_border_color #594141
url_color             #ffb3b6

active_tab_foreground   #68001a
active_tab_background   #ffb3b6
inactive_tab_foreground #e0bebf
inactive_tab_background #594141
cursor_trail_color      #e0bebf
